/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { ProviderWhereUniqueInput } from "../../provider/base/ProviderWhereUniqueInput";
import { ScheduleWhereUniqueInput } from "../../schedule/base/ScheduleWhereUniqueInput";
import { SyncLogListRelationFilter } from "../../syncLog/base/SyncLogListRelationFilter";
import { SyncTokenListRelationFilter } from "../../syncToken/base/SyncTokenListRelationFilter";

@InputType()
class CalendarWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  account?: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ProviderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProviderWhereUniqueInput)
  @IsOptional()
  @Field(() => ProviderWhereUniqueInput, {
    nullable: true,
  })
  provider?: ProviderWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ScheduleWhereUniqueInput)
  @IsOptional()
  @Field(() => ScheduleWhereUniqueInput, {
    nullable: true,
  })
  schedule?: ScheduleWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SyncLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SyncLogListRelationFilter)
  @IsOptional()
  @Field(() => SyncLogListRelationFilter, {
    nullable: true,
  })
  syncLogs?: SyncLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SyncTokenListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SyncTokenListRelationFilter)
  @IsOptional()
  @Field(() => SyncTokenListRelationFilter, {
    nullable: true,
  })
  syncTokens?: SyncTokenListRelationFilter;
}

export { CalendarWhereInput as CalendarWhereInput };
