/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProviderService } from "../provider.service";
import { ProviderCreateInput } from "./ProviderCreateInput";
import { Provider } from "./Provider";
import { ProviderFindManyArgs } from "./ProviderFindManyArgs";
import { ProviderWhereUniqueInput } from "./ProviderWhereUniqueInput";
import { ProviderUpdateInput } from "./ProviderUpdateInput";
import { CalendarFindManyArgs } from "../../calendar/base/CalendarFindManyArgs";
import { Calendar } from "../../calendar/base/Calendar";
import { CalendarWhereUniqueInput } from "../../calendar/base/CalendarWhereUniqueInput";

export class ProviderControllerBase {
  constructor(protected readonly service: ProviderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Provider })
  async createProvider(
    @common.Body() data: ProviderCreateInput
  ): Promise<Provider> {
    return await this.service.createProvider({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Provider] })
  @ApiNestedQuery(ProviderFindManyArgs)
  async providers(@common.Req() request: Request): Promise<Provider[]> {
    const args = plainToClass(ProviderFindManyArgs, request.query);
    return this.service.providers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Provider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async provider(
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<Provider | null> {
    const result = await this.service.provider({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Provider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProvider(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() data: ProviderUpdateInput
  ): Promise<Provider | null> {
    try {
      return await this.service.updateProvider({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Provider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProvider(
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<Provider | null> {
    try {
      return await this.service.deleteProvider({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/calendars")
  @ApiNestedQuery(CalendarFindManyArgs)
  async findCalendars(
    @common.Req() request: Request,
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<Calendar[]> {
    const query = plainToClass(CalendarFindManyArgs, request.query);
    const results = await this.service.findCalendars(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        account: {
          select: {
            id: true,
          },
        },

        provider: {
          select: {
            id: true,
          },
        },

        schedule: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/calendars")
  async connectCalendars(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: CalendarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      calendars: {
        connect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/calendars")
  async updateCalendars(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: CalendarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      calendars: {
        set: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/calendars")
  async disconnectCalendars(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: CalendarWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      calendars: {
        disconnect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }
}
